# This is a sample configuration to run an invotra instance with Docker-Compose.
# For customization options see: https://docs.docker.com/compose/yml/

webhead:
  image: dikini/apache-d7:latest
  links:
    - "db:db"
    - "solr"
    - "memcached"
  ports:
    - "80:80"
  volumes:
    - invotra:/var/www/html
db:
  image: mariadb
  container_name: invotra_db
  environment:
    - MYSQL_ROOT_PASSWORD=somepassword
memcached:
  image: memcached:latest
solr:
  image: dikini/solr_d7:latest
selenium-ff:
  image: selenium/standalone-firefox
  links:
    - webhead
  ports:
    - "4444:4444"
behat:
  build: behat
  dockerfile: Dockerfile.behat
  environment:
   - TEST=unused
   - TERM=xterm
  links:
    - selenium-ff
  volumes:
    - "/home/dikini/Projects/docker-invotra/automated-tests:/home/behat/automated-tests"